{
  config,
  lib,
  pkgs,
  ...
}:

let
  nvimPython = pkgs.python313.withPackages (
    pythonPackages: with pythonPackages; [
      ipykernel
      jupytext
      pynvim
    ]
  );
in
{
  home.packages = [ nvimPython ];

  home.sessionPath = [
    "${config.home.homeDirectory}/.bun/bin"
    "${config.home.homeDirectory}/.local/bin"
    "${config.home.homeDirectory}/bin"
    "/usr/local/go/bin"
  ];

  home.sessionVariables = {
    BUN_INSTALL = "${config.home.homeDirectory}/.bun";
    EDITOR = "nvim";
    NVIM_PYTHON3_HOST_PROG = "${nvimPython}/bin/python3";
    SOPS_AGE_KEY_FILE = "${config.xdg.configHome}/sops/age/keys.txt";
    VISUAL = "nvim";
  };

  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    shellAliases = {
      ".." = "cd ..";
      "..." = "cd ../..";
      conf = "nvim ~/.config/nix-conf/modules/home/mac-dotfiles.nix";
      k = "kubectl";
      ld = "lazydocker";
      lg = "lazygit";
      ls = "eza -ll";
      oarchive = "python3 ~/Documents/orgmode/org-archive.py";
      osync = "cd ~/Documents/obsidian-notes && git add . && git commit -m 'Quick sync' && git pull --rebase && git push";
      re = "exec zsh";
      rebuild = "cd ~/.config/nix-conf && sudo darwin-rebuild switch --flake 'path:.#macbook-pro'";
      tf = "terraform";
      todo = "nvim ~/Documents/orgmode/refile.org";
      v = "nvim";
      vim = "nvim";
    };

    initContent = lib.mkOrder 1000 ''
      setopt inc_append_history

      source ${config.xdg.configHome}/zsh/z.sh

      # API keys and machine-local exports belong here, never in Git.
      [[ -r ${config.xdg.configHome}/zsh/secrets.zsh ]] \
        && source ${config.xdg.configHome}/zsh/secrets.zsh

      # bun completions are installed outside Nix with bun itself.
      [[ -r "$BUN_INSTALL/_bun" ]] && source "$BUN_INSTALL/_bun"
    '';
  };

  # Secret-bearing values are loaded from an unmanaged local file. Use the
  # absolute target key generated by the zsh module so existing files are
  # adopted safely on first activation.
  home.file."${config.home.homeDirectory}/.zshrc".force = true;
  xdg.configFile."zsh/z.sh".source = ../../config/zsh/z.sh;

  programs.starship = {
    enable = true;
    enableZshIntegration = true;
    settings = builtins.fromTOML (builtins.readFile ../../config/starship.toml);
  };
  home.file."${config.xdg.configHome}/starship.toml".force = true;

  programs.tmux = {
    enable = true;
    shortcut = "p";
    baseIndex = 1;
    escapeTime = 0;
    keyMode = "vi";
    mouse = true;
    terminal = "tmux-256color";

    plugins = with pkgs.tmuxPlugins; [
      vim-tmux-navigator
      battery
      resurrect
      {
        plugin = continuum;
        extraConfig = "set -g @continuum-restore 'on'";
      }
    ];

    extraConfig = ''
      unbind r
      bind r source-file ${config.xdg.configHome}/tmux/tmux.conf

      bind-key h select-pane -L
      bind-key j select-pane -D
      bind-key k select-pane -U
      bind-key l select-pane -R

      bind | split-window -h
      bind - split-window -v
      unbind '"'
      unbind %

      set -g @batt_icon_charge_tier1 '󰁺'
      set -g @batt_icon_charge_tier2 '󰁼'
      set -g @batt_icon_charge_tier3 '󰁽'
      set -g @batt_icon_charge_tier4 '󰁾'
      set -g @batt_icon_charge_tier5 '󰁿'
      set -g @batt_icon_charge_tier6 '󰂀'
      set -g @batt_icon_charge_tier7 '󰂁'
      set -g @batt_icon_charge_tier8 '󰁹'
      set -g @batt_icon_status_charged '󰁹'
      set -g @batt_icon_status_charging '󰂄'

      set -g allow-passthrough on
      set -s extended-keys on
      set -as terminal-features 'xterm*:extkeys'
      set -as terminal-features 'tmux*:extkeys'
      set -ag terminal-overrides ',xterm-256color:RGB'
      set -g status-right '#{battery_icon} #{battery_percentage} | %a %h-%d %H:%M '
      set-option -g update-environment 'SSH_AUTH_SOCK'

      source-file ${config.xdg.configHome}/tmux/themes/token-flint-light.conf
    '';
  };

  # Keep the traditional path working while Home Manager generates the real
  # configuration under XDG_CONFIG_HOME.
  home.file.".tmux.conf" = {
    force = true;
    text = "source-file ${config.xdg.configHome}/tmux/tmux.conf\n";
  };
  xdg.configFile."tmux/themes/token-flint-light.conf" = {
    force = true;
    source = ../../config/tmux/themes/token-flint-light.conf;
  };

  # Keep the newer Homebrew Neovim binary, but make its complete configuration
  # an editable, repository-backed Home Manager symlink.
  xdg.configFile."nvim" = {
    force = true;
    source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.config/nix-conf/config/nvim";
  };
}
